### ISSUE TITLE
Update git snapshot

### ISSUE THREAD

**Issue by jabranham** [rejeep/evm#114] opened 2018-11-22 14:44 UTC
It looks like the git snapshot is about 9 months old. Any chance of updating is soon?

**Comment by rejeep** [comment] 2018-11-22 14:53
I guess you mean the Travis one? I never update this myself, but if someone wants to update it and provide me with a new file I'm happy to make a new release.

**Comment by jabranham** [comment] 2018-11-29 17:54
Pinging @sambrightman since it looks like he's done this before.

**Comment by rgoulter** [comment] 2018-12-22 17:35
Here's a build of emacs-git-snapshot from https://github.com/rgoulter/evm-travis-builds/releases/tag/20181222161457-50aa0cc

The travis script in rgoulter/evm-travis-builds (`git-snapshot` branch) adapts from #102 (which was written before #111).
"It should work" in terms of: it does the same thing the script from #102 did, which is the same thing the README says to do now. (#102 uses a Docker container to get a Travis-like environment. But Travis is also a Travis-like environment, so docker mightn't be necessary).
(And, again, #107: the git snapshot seems iffy anyway?).

AFAICT, e.g. #101, #107, the problem with emacs prebuilt binaries is:
- building an emacs with more features means more things need to be installed on the user end.
- building emacs without certain features means that emacs might not work for all use cases. (I'd guess that this is the cause for various issues filed here).

Since containers in travis builds can use packages in the whitelist, I don't think this is a big issue when the dependencies needed are in the safelist.
https://github.com/travis-ci/apt-package-safelist

I'd also think that automated emacs-*-travis builds would benefit from a fancier check than "is emacs there, does it have the right version".

(It'd also be an improvement to not have to PR/bump the snapshot recipe each time a new manual release was made).

**Comment by sambrightman** [comment] 2019-04-24 12:30
Fixed via #121.

**Closed by sambrightman** 2019-04-24 12:30 UTC
