### ISSUE TITLE
Issues with pretest and snapshot versions?

### ISSUE THREAD

**Issue by dieggsy** [rejeep/evm#100] opened 2017-11-22 16:05 UTC
Pretty new to all this, not really sure if this is a cask issue or an evm issue or something else entirely, but since the difference is the emacs version, I'm posting here:

I'm having an issue where when I try to test using emacs-26-pretest-travis and emacs-git-snapshot-travis, cask isn't able to connect to melpa (I think...). In any case, both tests error with `Package 's-' is unavailable`, as seen here:

https://travis-ci.org/dieggsy/difflib.el

**Comment by rejeep** [comment] 2017-11-22 18:47
I've seen that lately too, for example here https://travis-ci.org/rejeep/f.el/jobs/304338550. I don't know what the issue is, but most likely something with Emacs. Generating new tarballs might solve it if that's the case.

Closing this as those versions of Emacs are not released yet, hence not supported by either Cask nor Evm.

**Closed by rejeep** 2017-11-22 18:47 UTC

**Comment by sambrightman** [comment] 2017-11-22 20:14
Emacs removed fallback to the insecure `openssl s_client` method. Unreleased versions of EVM are built without gnutls support per the README (arguably this should be changed... it doesn't seem to match historical compilation of release versions). Despite the logs indicating that gnutls is failing, it is probably just not installed in your Travis environment (it is whitelisted and can be installed using the apt addon). See melpa/melpa#5109.

**Comment by dieggsy** [comment] 2017-11-22 22:04
@sambrightman thanks, that seemed to solve the issue
